### ISSUE TITLE
Update for 1.8.86 (11/20/23)

### ISSUE THREAD

**Issue by fromanan** [ianpatt/sfse#23]
SFSE will not boot for the latest game runtime via Steam

This is not meant to complain, just to put it on your guys' radar :) love your work!! Cheers

**Comment by asaf400** [comment]
It is possible to downgrade the game version in order to play it as v1.7.36.0
For those who's game just update to version 1.8,
It's quite easy actually, Just open up steam internal console by openning the link:

steam://nav/console

Then you download the previous versions of the 2 depots of the game (Binaries + Content)
By running these commands in the console (1st one should take a minute, 2nd is longer)
MAKE SURE YOU HAVE DISK SPACE (13GB is enough for the difference)

download_depot 1716740 1716741 5786973905162837596 7109517847119257269
download_depot 1716740 1716742 5161319454857509031 7798731510825991201

While it's downloading the big content change, go here, and remove all the 'Added' files from the game directory,
if you do not remove them, You windows might bluescreen - no joke, it messes up the nvidia driver if you do not remove them
https://steamdb.info/depot/1716741/history/?changeid=M:7109517847119257269

This is the list of files to delete:
 Added – NRD.dll (14.82 MiB)
 Added – NvLowLatencyVk.dll (56.46 KiB)
 Added – nvngx_dlss.dll (49.32 MiB)
 Added – nvngx_dlssg.dll (12.00 MiB)
 Added – sl.common.dll (600.96 KiB)
 Added – sl.dlss.dll (199.47 KiB)
 Added – sl.dlss_g.dll (356.47 KiB)
 Added – sl.interposer.dll (498.96 KiB)
 Added – sl.nis.dll (904.47 KiB)
 Added – sl.nrd.dll (212.97 KiB)
 Added – sl.reflex.dll (141.47 KiB)

After both downloads finish, just copy all the files from each download dir into the game dir, Steam tells you where it has downloaded the files, most commnly it would be in:
C:\Program Files (x86)\Steam\steamapps\content\app_1716740

**Comment by Daigoji-Gai** [comment]
> SFSE will not boot for the latest game runtime via Steam
> 
> This is not meant to complain, just to put it on your guys' radar :) love your work!! Cheers

FYI - they know. They have been supporting BethSoft games for over a decade with the Script Extenders. This will always happen, so don't have your game auto-update. Given Starfield is still a relatively new game early in bethsoft's release cycle, expect this to happen regularly as Bethsoft patches and us modders have to play catch up. The beta branches on steam are helping, but it will still take time. So Pro-Tip: Disable auto game updates and be prepared to wait 24-72 hours (if not more if modders is taking a break) for SE and any mods dependent on it to be updated.

**Comment by fromanan** [comment]
Thanks guys, I've got my game restored back to the working version!

**Comment by asaf400** [comment]
Andd.. It's out :)

https://www.nexusmods.com/starfield/mods/106?tab=files

**Comment by asaf400** [comment]
@ianpatt Maybe add the method to downgrade in the README.md or in nexus page?

This is going to happen multiple times in the future with starfield patches.
+Kudos for the fast release 🎉
