### ISSUE TITLE
Update automation

### ISSUE THREAD

**Issue by imax9000** [ianpatt/sfse#35]
I'm curious: how do you handle game updates?

I suspect you already have some automation in place to extract all the addresses from a new game binaries and updating them in the source code. (Can't imagine anyone going over every single one of them by hand)

But I can't seem to find any of the automation in this repo.

**Comment by ianpatt** [comment]
I have been working on binary comparison tooling since BGS started getting overactive with patching. Two versions have been based on position-independent code hashes. The current version is a lot more complicated, with the short explanation being extremely heavy cross-reference building and code analysis.

The code or binaries are unlikely to be released, sorry.
