### ISSUE TITLE
License clarification - is SFSE open source or not?

### ISSUE THREAD

**Issue by JMPZ11** [ianpatt/sfse#39]
I'm trying to understand the license terms -- sfse/LICENSE contains what looks like modified MIT wording, but says it only applies to a single file out of a sizeable project: `sfse/PluginAPI.h`. A header at that.

At the end it states `The remainder of the files are currently not under a permissive license.` What does this mean? What license applies to the remainder of the files?

I was aware that some of the reverse engineered APIs had switched to strict FOSS terms, but I had been of the understanding that SFSE was MIT licensed (not sure if it changed or I was misinformed)

Thanks!

**Comment by ianpatt** [comment]
Licenses exist to grant additional rights on top of what is provided by default copyright law, often with specific restrictions on that use.

PluginAPI.h is MIT licensed so that anyone can make plugins. No additional portions (other than the plugin API) of the script extenders have ever been MIT licensed. There is no license granting additional rights to the rest of the files, and the project is not Open Source.

**Comment by JMPZ11** [comment]
Thanks for the clarification - it was indeed my misunderstanding
